/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Error from './Error';
import Meta from './Meta';

/**
 * The GetHealth200Response model module.
 * @module model/GetHealth200Response
 * @version 0.1.0
 */
class GetHealth200Response {
    /**
     * @member {String} data
     * @type {String}
     */
    data;
    /**
     * @member {module:model/Error} error
     * @type {module:model/Error}
     */
    error;
    /**
     * @member {module:model/Meta} meta
     * @type {module:model/Meta}
     */
    meta;
    /**
     * @member {Boolean} success
     * @type {Boolean}
     */
    success;

    

    /**
     * Constructs a new <code>GetHealth200Response</code>.
     * @alias module:model/GetHealth200Response
     * @param success {Boolean} 
     */
    constructor(success) { 
        
        GetHealth200Response.initialize(this, success);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success) { 
        obj['success'] = success;
    }

    /**
     * Constructs a <code>GetHealth200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetHealth200Response} obj Optional instance to populate.
     * @return {module:model/GetHealth200Response} The populated <code>GetHealth200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetHealth200Response();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = Error.constructFromObject(data['error']);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = Meta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
        }
        return obj;
    }
}



export default GetHealth200Response;

