/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV1RunnerChatRequestMessagesInner model module.
 * @module model/PostV1RunnerChatRequestMessagesInner
 * @version 0.1.0
 */
class PostV1RunnerChatRequestMessagesInner {
    /**
     * @member {String} content
     * @type {String}
     */
    content;
    /**
     * @member {String} role
     * @type {String}
     */
    role;

    

    /**
     * Constructs a new <code>PostV1RunnerChatRequestMessagesInner</code>.
     * @alias module:model/PostV1RunnerChatRequestMessagesInner
     * @param content {String} 
     * @param role {String} 
     */
    constructor(content, role) { 
        
        PostV1RunnerChatRequestMessagesInner.initialize(this, content, role);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content, role) { 
        obj['content'] = content;
        obj['role'] = role;
    }

    /**
     * Constructs a <code>PostV1RunnerChatRequestMessagesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1RunnerChatRequestMessagesInner} obj Optional instance to populate.
     * @return {module:model/PostV1RunnerChatRequestMessagesInner} The populated <code>PostV1RunnerChatRequestMessagesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1RunnerChatRequestMessagesInner();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
        }
        return obj;
    }
}



export default PostV1RunnerChatRequestMessagesInner;

