/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostV1RunnerChatRequestMessagesInner from './PostV1RunnerChatRequestMessagesInner';

/**
 * The PostV1RunnerChatRequest model module.
 * @module model/PostV1RunnerChatRequest
 * @version 0.1.0
 */
class PostV1RunnerChatRequest {
    /**
     * @member {Array.<module:model/PostV1RunnerChatRequestMessagesInner>} messages
     * @type {Array.<module:model/PostV1RunnerChatRequestMessagesInner>}
     */
    messages;

    

    /**
     * Constructs a new <code>PostV1RunnerChatRequest</code>.
     * @alias module:model/PostV1RunnerChatRequest
     * @param messages {Array.<module:model/PostV1RunnerChatRequestMessagesInner>} 
     */
    constructor(messages) { 
        
        PostV1RunnerChatRequest.initialize(this, messages);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, messages) { 
        obj['messages'] = messages;
    }

    /**
     * Constructs a <code>PostV1RunnerChatRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1RunnerChatRequest} obj Optional instance to populate.
     * @return {module:model/PostV1RunnerChatRequest} The populated <code>PostV1RunnerChatRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1RunnerChatRequest();

            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], [PostV1RunnerChatRequestMessagesInner]);
            }
        }
        return obj;
    }
}



export default PostV1RunnerChatRequest;

