/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV1RunnerChat200ResponseData model module.
 * @module model/PostV1RunnerChat200ResponseData
 * @version 0.1.0
 */
class PostV1RunnerChat200ResponseData {
    /**
     * @member {String} reply
     * @type {String}
     */
    reply;

    

    /**
     * Constructs a new <code>PostV1RunnerChat200ResponseData</code>.
     * @alias module:model/PostV1RunnerChat200ResponseData
     */
    constructor() { 
        
        PostV1RunnerChat200ResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV1RunnerChat200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1RunnerChat200ResponseData} obj Optional instance to populate.
     * @return {module:model/PostV1RunnerChat200ResponseData} The populated <code>PostV1RunnerChat200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1RunnerChat200ResponseData();

            if (data.hasOwnProperty('reply')) {
                obj['reply'] = ApiClient.convertToType(data['reply'], 'String');
            }
        }
        return obj;
    }
}



export default PostV1RunnerChat200ResponseData;

