/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV1RunnerGenerateRequest model module.
 * @module model/PostV1RunnerGenerateRequest
 * @version 0.1.0
 */
class PostV1RunnerGenerateRequest {
    /**
     * @member {String} prompt
     * @type {String}
     */
    prompt;

    

    /**
     * Constructs a new <code>PostV1RunnerGenerateRequest</code>.
     * @alias module:model/PostV1RunnerGenerateRequest
     * @param prompt {String} 
     */
    constructor(prompt) { 
        
        PostV1RunnerGenerateRequest.initialize(this, prompt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, prompt) { 
        obj['prompt'] = prompt;
    }

    /**
     * Constructs a <code>PostV1RunnerGenerateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1RunnerGenerateRequest} obj Optional instance to populate.
     * @return {module:model/PostV1RunnerGenerateRequest} The populated <code>PostV1RunnerGenerateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1RunnerGenerateRequest();

            if (data.hasOwnProperty('prompt')) {
                obj['prompt'] = ApiClient.convertToType(data['prompt'], 'String');
            }
        }
        return obj;
    }
}



export default PostV1RunnerGenerateRequest;

