/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */



import ApiClient from "../ApiClient";
import GetHealth429Response from '../model/GetHealth429Response';
import GetV1RunnerModels200Response from '../model/GetV1RunnerModels200Response';
import PostV1RunnerChat200Response from '../model/PostV1RunnerChat200Response';
import PostV1RunnerChatRequest from '../model/PostV1RunnerChatRequest';
import PostV1RunnerGenerateRequest from '../model/PostV1RunnerGenerateRequest';

/**
* Runner service.
* @module api/RunnerApi
* @version 0.1.0
*/
export default class RunnerApi extends ApiClient {

    /**
    * Constructs a new RunnerApi. 
    * @alias module:api/RunnerApi
    * @class
    */
    constructor(baseURL = 'http://localhost') {
      super(baseURL);
    }


    /**
     * List configured runner model routes
     * 
     * @param requestInit Dynamic configuration. @see {@link https://github.com/apollographql/apollo-server/pull/1277}
     * @return {Promise<module:model/GetV1RunnerModels200Response>}
     */
    async getV1RunnerModels(requestInit) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'User-Agent': 'OpenAPI-Generator/0.1.0/Javascript',
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetV1RunnerModels200Response;

      return this.callApi(
        '/v1/runner/models', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, requestInit
      );
    }

    /**
     * Multi-turn chat completion
     * 
     * @param {module:model/PostV1RunnerChatRequest} postV1RunnerChatRequest 
     * @param requestInit Dynamic configuration. @see {@link https://github.com/apollographql/apollo-server/pull/1277}
     * @return {Promise<module:model/PostV1RunnerChat200Response>}
     */
    async postV1RunnerChat(postV1RunnerChatRequest, requestInit) {
      let postBody = postV1RunnerChatRequest;
      // verify the required parameter 'postV1RunnerChatRequest' is set
      if (postV1RunnerChatRequest === undefined || postV1RunnerChatRequest === null) {
        throw new Error("Missing the required parameter 'postV1RunnerChatRequest' when calling postV1RunnerChat");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'User-Agent': 'OpenAPI-Generator/0.1.0/Javascript',
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV1RunnerChat200Response;

      return this.callApi(
        '/v1/runner/chat', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, requestInit
      );
    }

    /**
     * Single-prompt generation
     * 
     * @param {module:model/PostV1RunnerGenerateRequest} postV1RunnerGenerateRequest 
     * @param requestInit Dynamic configuration. @see {@link https://github.com/apollographql/apollo-server/pull/1277}
     * @return {Promise<module:model/PostV1RunnerChat200Response>}
     */
    async postV1RunnerGenerate(postV1RunnerGenerateRequest, requestInit) {
      let postBody = postV1RunnerGenerateRequest;
      // verify the required parameter 'postV1RunnerGenerateRequest' is set
      if (postV1RunnerGenerateRequest === undefined || postV1RunnerGenerateRequest === null) {
        throw new Error("Missing the required parameter 'postV1RunnerGenerateRequest' when calling postV1RunnerGenerate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'User-Agent': 'OpenAPI-Generator/0.1.0/Javascript',
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostV1RunnerChat200Response;

      return this.callApi(
        '/v1/runner/generate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, requestInit
      );
    }


}
