/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */



import ApiClient from "../ApiClient";
import GetHealth200Response from '../model/GetHealth200Response';
import GetHealth429Response from '../model/GetHealth429Response';

/**
* System service.
* @module api/SystemApi
* @version 0.1.0
*/
export default class SystemApi extends ApiClient {

    /**
    * Constructs a new SystemApi. 
    * @alias module:api/SystemApi
    * @class
    */
    constructor(baseURL = 'http://localhost') {
      super(baseURL);
    }


    /**
     * Health check
     * Returns server health status
     * @param requestInit Dynamic configuration. @see {@link https://github.com/apollographql/apollo-server/pull/1277}
     * @return {Promise<module:model/GetHealth200Response>}
     */
    async getHealth(requestInit) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'User-Agent': 'OpenAPI-Generator/0.1.0/Javascript',
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetHealth200Response;

      return this.callApi(
        '/health', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, requestInit
      );
    }


}
