/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LthnApi);
  }
}(this, function(expect, LthnApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LthnApi.PostV1RunnerChat200ResponseData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostV1RunnerChat200ResponseData', function() {
    it('should create an instance of PostV1RunnerChat200ResponseData', function() {
      // uncomment below and update the code to test PostV1RunnerChat200ResponseData
      //var instance = new LthnApi.PostV1RunnerChat200ResponseData();
      //expect(instance).to.be.a(LthnApi.PostV1RunnerChat200ResponseData);
    });

    it('should have the property reply (base name: "reply")', function() {
      // uncomment below and update the code to test the property reply
      //var instance = new LthnApi.PostV1RunnerChat200ResponseData();
      //expect(instance).to.be();
    });

  });

}));
