/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Error from './model/Error';
import GetHealth200Response from './model/GetHealth200Response';
import GetHealth429Response from './model/GetHealth429Response';
import GetV1RunnerModels200Response from './model/GetV1RunnerModels200Response';
import GetV1RunnerModels200ResponseData from './model/GetV1RunnerModels200ResponseData';
import Meta from './model/Meta';
import PostV1RunnerChat200Response from './model/PostV1RunnerChat200Response';
import PostV1RunnerChat200ResponseData from './model/PostV1RunnerChat200ResponseData';
import PostV1RunnerChatRequest from './model/PostV1RunnerChatRequest';
import PostV1RunnerChatRequestMessagesInner from './model/PostV1RunnerChatRequestMessagesInner';
import PostV1RunnerGenerateRequest from './model/PostV1RunnerGenerateRequest';
import Response from './model/Response';
import RunnerApi from './api/RunnerApi';
import SystemApi from './api/SystemApi';


/**
* Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var LthnApi = require('index'); // See note below*.
* var xxxSvc = new LthnApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new LthnApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new LthnApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new LthnApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The GetHealth200Response model constructor.
     * @property {module:model/GetHealth200Response}
     */
    GetHealth200Response,

    /**
     * The GetHealth429Response model constructor.
     * @property {module:model/GetHealth429Response}
     */
    GetHealth429Response,

    /**
     * The GetV1RunnerModels200Response model constructor.
     * @property {module:model/GetV1RunnerModels200Response}
     */
    GetV1RunnerModels200Response,

    /**
     * The GetV1RunnerModels200ResponseData model constructor.
     * @property {module:model/GetV1RunnerModels200ResponseData}
     */
    GetV1RunnerModels200ResponseData,

    /**
     * The Meta model constructor.
     * @property {module:model/Meta}
     */
    Meta,

    /**
     * The PostV1RunnerChat200Response model constructor.
     * @property {module:model/PostV1RunnerChat200Response}
     */
    PostV1RunnerChat200Response,

    /**
     * The PostV1RunnerChat200ResponseData model constructor.
     * @property {module:model/PostV1RunnerChat200ResponseData}
     */
    PostV1RunnerChat200ResponseData,

    /**
     * The PostV1RunnerChatRequest model constructor.
     * @property {module:model/PostV1RunnerChatRequest}
     */
    PostV1RunnerChatRequest,

    /**
     * The PostV1RunnerChatRequestMessagesInner model constructor.
     * @property {module:model/PostV1RunnerChatRequestMessagesInner}
     */
    PostV1RunnerChatRequestMessagesInner,

    /**
     * The PostV1RunnerGenerateRequest model constructor.
     * @property {module:model/PostV1RunnerGenerateRequest}
     */
    PostV1RunnerGenerateRequest,

    /**
     * The Response model constructor.
     * @property {module:model/Response}
     */
    Response,

    /**
    * The RunnerApi service constructor.
    * @property {module:api/RunnerApi}
    */
    RunnerApi,

    /**
    * The SystemApi service constructor.
    * @property {module:api/SystemApi}
    */
    SystemApi
};
