/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  }
}(this, function(expect, LthnApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LthnApi.RunnerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RunnerApi', function() {
    describe('getV1RunnerModels', function() {
      it('should call getV1RunnerModels successfully', function(done) {
        //uncomment below and update the code to test getV1RunnerModels
        //instance.getV1RunnerModels(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1RunnerChat', function() {
      it('should call postV1RunnerChat successfully', function(done) {
        //uncomment below and update the code to test postV1RunnerChat
        //instance.postV1RunnerChat(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1RunnerGenerate', function() {
      it('should call postV1RunnerGenerate successfully', function(done) {
        //uncomment below and update the code to test postV1RunnerGenerate
        //instance.postV1RunnerGenerate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
